/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.br.training.dto.ProductDTO;
import com.br.training.repository.InMemoryProductRepository;
import com.br.training.service.ProductService;

public class App {
    public String getGreeting() {
        return "Hello World Gradle Fabiano";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
        ProductService service = new ProductService(new InMemoryProductRepository());
        
        
     service.createProduct(new ProductDTO(1L, "Product A", "R$", 10, 99.99));
     boolean salvou = service.createProduct(new ProductDTO(2L, "Product B", "$", 5, 100.00));
        System.out.println("Product saved: " + salvou);
       service.getAllProducts().forEach(p -> 
			System.out.println("Product: " + p.name() + ", Price: "+p.decription() + p.price())			
		);        
        
    }    
}
