/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Test;

public class AppTest {
    
	@Test 
    public void appHasAGreeting() {
        App classUnderTest = new App();
        assertEquals("Hello World Gradle Fabiano", classUnderTest.getGreeting());  
        assertNotNull("app teste", classUnderTest.getGreeting());
    }
}
